version: "3.8"
services:
  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis:/var/lib/redis
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017'
    networks:
      - mynetwork
    volumes:
      - ./db/mongo:/var/lib/mongo
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_crud
    volumes:
      - ./db/postgres:/var/lib/postgresql
    ports:
      - "5436:5432"
networks:
  mynetwork:
    driver: bridge
  redis:
